type: "diff_drive_controller/DiffDriveController"
publish_rate: 50

right_wheel: ['base_to_rigth_legwhell_1_1', 'base_to_rigth_legwhell_2_1','base_to_rigth_legwhell_3_1']
left_wheel: ['base_to_left_legwhell_1_1', 'base_to_left_legwhell_2_1','base_to_left_legwhell_3_1']

wheel_separation: 0.66

pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]

base_frame_id: base_link

linear:
  x:
    has_velocity_limits : true
    max_velocity : 0.3 
    has_acceleration_limits: true
    max_acceleration : 0.8
angular:
  z:
    has_velocity_limits : true
    max_velocity : 0.3
    has_acceleration_limits: true
    max_acceleration : 0.8
